/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as DecideRouteImport } from './routes/decide'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as OrderCompleteRouteImport } from './routes/order-complete'
import { Route as PremiumRouteImport } from './routes/premium'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiDailyRouteImport } from './routes/api/daily'
import { Route as ApiHouseholdRouteImport } from './routes/api/household'
import { Route as ApiMenuRouteImport } from './routes/api/menu'
import { Route as ApiNewsRouteImport } from './routes/api/news'
import { Route as ApiOrderTogetherRouteImport } from './routes/api/order-together'
import { Route as ApiPremiumStatusRouteImport } from './routes/api/premium-status'
import { Route as ApiSuggestRouteImport } from './routes/api/suggest'
import { Route as ApiWhopEventsRouteImport } from './routes/api/whop-events'
import { Route as CheckoutPlanIdRouteImport } from './routes/checkout.$planId'
import { Route as DecideSplatRouteImport } from './routes/decide/$'
import { Route as EatIndexRouteImport } from './routes/eat.index'
import { Route as EatDishRouteImport } from './routes/eat.$dish'
import { Route as ExperiencesExperienceIdRouteImport } from './routes/experiences.$experienceId'
import { Route as SeatIdRouteImport } from './routes/seat.$id'
import { Route as TogetherCodeRouteImport } from './routes/together.$code'
import { Route as ApiOauthCallbackRouteImport } from './routes/api/oauth/callback'
import { Route as ApiOauthLoginRouteImport } from './routes/api/oauth/login'
import { Route as ApiOauthLogoutRouteImport } from './routes/api/oauth/logout'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const DecideRoute = DecideRouteImport.update({
  id: '/decide',
  path: '/decide',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderCompleteRoute = OrderCompleteRouteImport.update({
  id: '/order-complete',
  path: '/order-complete',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumRoute = PremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDailyRoute = ApiDailyRouteImport.update({
  id: '/api/daily',
  path: '/api/daily',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHouseholdRoute = ApiHouseholdRouteImport.update({
  id: '/api/household',
  path: '/api/household',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMenuRoute = ApiMenuRouteImport.update({
  id: '/api/menu',
  path: '/api/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNewsRoute = ApiNewsRouteImport.update({
  id: '/api/news',
  path: '/api/news',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrderTogetherRoute = ApiOrderTogetherRouteImport.update({
  id: '/api/order-together',
  path: '/api/order-together',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPremiumStatusRoute = ApiPremiumStatusRouteImport.update({
  id: '/api/premium-status',
  path: '/api/premium-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSuggestRoute = ApiSuggestRouteImport.update({
  id: '/api/suggest',
  path: '/api/suggest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWhopEventsRoute = ApiWhopEventsRouteImport.update({
  id: '/api/whop-events',
  path: '/api/whop-events',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutPlanIdRoute = CheckoutPlanIdRouteImport.update({
  id: '/checkout/$planId',
  path: '/checkout/$planId',
  getParentRoute: () => rootRouteImport,
} as any)
const DecideSplatRoute = DecideSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => DecideRoute,
} as any)
const EatIndexRoute = EatIndexRouteImport.update({
  id: '/eat/',
  path: '/eat/',
  getParentRoute: () => rootRouteImport,
} as any)
const EatDishRoute = EatDishRouteImport.update({
  id: '/eat/$dish',
  path: '/eat/$dish',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperiencesExperienceIdRoute = ExperiencesExperienceIdRouteImport.update({
  id: '/experiences/$experienceId',
  path: '/experiences/$experienceId',
  getParentRoute: () => rootRouteImport,
} as any)
const SeatIdRoute = SeatIdRouteImport.update({
  id: '/seat/$id',
  path: '/seat/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TogetherCodeRoute = TogetherCodeRouteImport.update({
  id: '/together/$code',
  path: '/together/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOauthCallbackRoute = ApiOauthCallbackRouteImport.update({
  id: '/api/oauth/callback',
  path: '/api/oauth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOauthLoginRoute = ApiOauthLoginRouteImport.update({
  id: '/api/oauth/login',
  path: '/api/oauth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOauthLogoutRoute = ApiOauthLogoutRouteImport.update({
  id: '/api/oauth/logout',
  path: '/api/oauth/logout',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/decide': typeof DecideRouteWithChildren
  '/faq': typeof FaqRoute
  '/how-it-works': typeof HowItWorksRoute
  '/order-complete': typeof OrderCompleteRoute
  '/premium': typeof PremiumRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/chat': typeof ApiChatRoute
  '/api/daily': typeof ApiDailyRoute
  '/api/household': typeof ApiHouseholdRoute
  '/api/menu': typeof ApiMenuRoute
  '/api/news': typeof ApiNewsRoute
  '/api/order-together': typeof ApiOrderTogetherRoute
  '/api/premium-status': typeof ApiPremiumStatusRoute
  '/api/suggest': typeof ApiSuggestRoute
  '/api/whop-events': typeof ApiWhopEventsRoute
  '/checkout/$planId': typeof CheckoutPlanIdRoute
  '/decide/$': typeof DecideSplatRoute
  '/eat/$dish': typeof EatDishRoute
  '/experiences/$experienceId': typeof ExperiencesExperienceIdRoute
  '/seat/$id': typeof SeatIdRoute
  '/together/$code': typeof TogetherCodeRoute
  '/eat/': typeof EatIndexRoute
  '/api/oauth/callback': typeof ApiOauthCallbackRoute
  '/api/oauth/login': typeof ApiOauthLoginRoute
  '/api/oauth/logout': typeof ApiOauthLogoutRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/decide': typeof DecideRouteWithChildren
  '/faq': typeof FaqRoute
  '/how-it-works': typeof HowItWorksRoute
  '/order-complete': typeof OrderCompleteRoute
  '/premium': typeof PremiumRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/chat': typeof ApiChatRoute
  '/api/daily': typeof ApiDailyRoute
  '/api/household': typeof ApiHouseholdRoute
  '/api/menu': typeof ApiMenuRoute
  '/api/news': typeof ApiNewsRoute
  '/api/order-together': typeof ApiOrderTogetherRoute
  '/api/premium-status': typeof ApiPremiumStatusRoute
  '/api/suggest': typeof ApiSuggestRoute
  '/api/whop-events': typeof ApiWhopEventsRoute
  '/checkout/$planId': typeof CheckoutPlanIdRoute
  '/decide/$': typeof DecideSplatRoute
  '/eat/$dish': typeof EatDishRoute
  '/experiences/$experienceId': typeof ExperiencesExperienceIdRoute
  '/seat/$id': typeof SeatIdRoute
  '/together/$code': typeof TogetherCodeRoute
  '/eat': typeof EatIndexRoute
  '/api/oauth/callback': typeof ApiOauthCallbackRoute
  '/api/oauth/login': typeof ApiOauthLoginRoute
  '/api/oauth/logout': typeof ApiOauthLogoutRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/decide': typeof DecideRouteWithChildren
  '/faq': typeof FaqRoute
  '/how-it-works': typeof HowItWorksRoute
  '/order-complete': typeof OrderCompleteRoute
  '/premium': typeof PremiumRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/chat': typeof ApiChatRoute
  '/api/daily': typeof ApiDailyRoute
  '/api/household': typeof ApiHouseholdRoute
  '/api/menu': typeof ApiMenuRoute
  '/api/news': typeof ApiNewsRoute
  '/api/order-together': typeof ApiOrderTogetherRoute
  '/api/premium-status': typeof ApiPremiumStatusRoute
  '/api/suggest': typeof ApiSuggestRoute
  '/api/whop-events': typeof ApiWhopEventsRoute
  '/checkout/$planId': typeof CheckoutPlanIdRoute
  '/decide/$': typeof DecideSplatRoute
  '/eat/$dish': typeof EatDishRoute
  '/experiences/$experienceId': typeof ExperiencesExperienceIdRoute
  '/seat/$id': typeof SeatIdRoute
  '/together/$code': typeof TogetherCodeRoute
  '/eat/': typeof EatIndexRoute
  '/api/oauth/callback': typeof ApiOauthCallbackRoute
  '/api/oauth/login': typeof ApiOauthLoginRoute
  '/api/oauth/logout': typeof ApiOauthLogoutRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/decide'
    | '/faq'
    | '/how-it-works'
    | '/order-complete'
    | '/premium'
    | '/privacy'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/chat'
    | '/api/daily'
    | '/api/household'
    | '/api/menu'
    | '/api/news'
    | '/api/order-together'
    | '/api/premium-status'
    | '/api/suggest'
    | '/api/whop-events'
    | '/checkout/$planId'
    | '/decide/$'
    | '/eat/$dish'
    | '/experiences/$experienceId'
    | '/seat/$id'
    | '/together/$code'
    | '/eat/'
    | '/api/oauth/callback'
    | '/api/oauth/login'
    | '/api/oauth/logout'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/decide'
    | '/faq'
    | '/how-it-works'
    | '/order-complete'
    | '/premium'
    | '/privacy'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/chat'
    | '/api/daily'
    | '/api/household'
    | '/api/menu'
    | '/api/news'
    | '/api/order-together'
    | '/api/premium-status'
    | '/api/suggest'
    | '/api/whop-events'
    | '/checkout/$planId'
    | '/decide/$'
    | '/eat/$dish'
    | '/experiences/$experienceId'
    | '/seat/$id'
    | '/together/$code'
    | '/eat'
    | '/api/oauth/callback'
    | '/api/oauth/login'
    | '/api/oauth/logout'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/decide'
    | '/faq'
    | '/how-it-works'
    | '/order-complete'
    | '/premium'
    | '/privacy'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/chat'
    | '/api/daily'
    | '/api/household'
    | '/api/menu'
    | '/api/news'
    | '/api/order-together'
    | '/api/premium-status'
    | '/api/suggest'
    | '/api/whop-events'
    | '/checkout/$planId'
    | '/decide/$'
    | '/eat/$dish'
    | '/experiences/$experienceId'
    | '/seat/$id'
    | '/together/$code'
    | '/eat/'
    | '/api/oauth/callback'
    | '/api/oauth/login'
    | '/api/oauth/logout'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  DecideRoute: typeof DecideRouteWithChildren
  FaqRoute: typeof FaqRoute
  HowItWorksRoute: typeof HowItWorksRoute
  OrderCompleteRoute: typeof OrderCompleteRoute
  PremiumRoute: typeof PremiumRoute
  PrivacyRoute: typeof PrivacyRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiDailyRoute: typeof ApiDailyRoute
  ApiHouseholdRoute: typeof ApiHouseholdRoute
  ApiMenuRoute: typeof ApiMenuRoute
  ApiNewsRoute: typeof ApiNewsRoute
  ApiOrderTogetherRoute: typeof ApiOrderTogetherRoute
  ApiPremiumStatusRoute: typeof ApiPremiumStatusRoute
  ApiSuggestRoute: typeof ApiSuggestRoute
  ApiWhopEventsRoute: typeof ApiWhopEventsRoute
  CheckoutPlanIdRoute: typeof CheckoutPlanIdRoute
  EatDishRoute: typeof EatDishRoute
  ExperiencesExperienceIdRoute: typeof ExperiencesExperienceIdRoute
  SeatIdRoute: typeof SeatIdRoute
  TogetherCodeRoute: typeof TogetherCodeRoute
  EatIndexRoute: typeof EatIndexRoute
  ApiOauthCallbackRoute: typeof ApiOauthCallbackRoute
  ApiOauthLoginRoute: typeof ApiOauthLoginRoute
  ApiOauthLogoutRoute: typeof ApiOauthLogoutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decide': {
      id: '/decide'
      path: '/decide'
      fullPath: '/decide'
      preLoaderRoute: typeof DecideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-complete': {
      id: '/order-complete'
      path: '/order-complete'
      fullPath: '/order-complete'
      preLoaderRoute: typeof OrderCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium': {
      id: '/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof PremiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/daily': {
      id: '/api/daily'
      path: '/api/daily'
      fullPath: '/api/daily'
      preLoaderRoute: typeof ApiDailyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/household': {
      id: '/api/household'
      path: '/api/household'
      fullPath: '/api/household'
      preLoaderRoute: typeof ApiHouseholdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/menu': {
      id: '/api/menu'
      path: '/api/menu'
      fullPath: '/api/menu'
      preLoaderRoute: typeof ApiMenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/news': {
      id: '/api/news'
      path: '/api/news'
      fullPath: '/api/news'
      preLoaderRoute: typeof ApiNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/order-together': {
      id: '/api/order-together'
      path: '/api/order-together'
      fullPath: '/api/order-together'
      preLoaderRoute: typeof ApiOrderTogetherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/premium-status': {
      id: '/api/premium-status'
      path: '/api/premium-status'
      fullPath: '/api/premium-status'
      preLoaderRoute: typeof ApiPremiumStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/suggest': {
      id: '/api/suggest'
      path: '/api/suggest'
      fullPath: '/api/suggest'
      preLoaderRoute: typeof ApiSuggestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/whop-events': {
      id: '/api/whop-events'
      path: '/api/whop-events'
      fullPath: '/api/whop-events'
      preLoaderRoute: typeof ApiWhopEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$planId': {
      id: '/checkout/$planId'
      path: '/checkout/$planId'
      fullPath: '/checkout/$planId'
      preLoaderRoute: typeof CheckoutPlanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decide/$': {
      id: '/decide/$'
      path: '/$'
      fullPath: '/decide/$'
      preLoaderRoute: typeof DecideSplatRouteImport
      parentRoute: typeof DecideRoute
    }
    '/eat/': {
      id: '/eat/'
      path: '/eat'
      fullPath: '/eat/'
      preLoaderRoute: typeof EatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eat/$dish': {
      id: '/eat/$dish'
      path: '/eat/$dish'
      fullPath: '/eat/$dish'
      preLoaderRoute: typeof EatDishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiences/$experienceId': {
      id: '/experiences/$experienceId'
      path: '/experiences/$experienceId'
      fullPath: '/experiences/$experienceId'
      preLoaderRoute: typeof ExperiencesExperienceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seat/$id': {
      id: '/seat/$id'
      path: '/seat/$id'
      fullPath: '/seat/$id'
      preLoaderRoute: typeof SeatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/together/$code': {
      id: '/together/$code'
      path: '/together/$code'
      fullPath: '/together/$code'
      preLoaderRoute: typeof TogetherCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oauth/callback': {
      id: '/api/oauth/callback'
      path: '/api/oauth/callback'
      fullPath: '/api/oauth/callback'
      preLoaderRoute: typeof ApiOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oauth/login': {
      id: '/api/oauth/login'
      path: '/api/oauth/login'
      fullPath: '/api/oauth/login'
      preLoaderRoute: typeof ApiOauthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oauth/logout': {
      id: '/api/oauth/logout'
      path: '/api/oauth/logout'
      fullPath: '/api/oauth/logout'
      preLoaderRoute: typeof ApiOauthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DecideRouteChildren {
  DecideSplatRoute: typeof DecideSplatRoute
}

const DecideRouteChildren: DecideRouteChildren = {
  DecideSplatRoute: DecideSplatRoute,
}

const DecideRouteWithChildren =
  DecideRoute._addFileChildren(DecideRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  DecideRoute: DecideRouteWithChildren,
  FaqRoute: FaqRoute,
  HowItWorksRoute: HowItWorksRoute,
  OrderCompleteRoute: OrderCompleteRoute,
  PremiumRoute: PremiumRoute,
  PrivacyRoute: PrivacyRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiChatRoute: ApiChatRoute,
  ApiDailyRoute: ApiDailyRoute,
  ApiHouseholdRoute: ApiHouseholdRoute,
  ApiMenuRoute: ApiMenuRoute,
  ApiNewsRoute: ApiNewsRoute,
  ApiOrderTogetherRoute: ApiOrderTogetherRoute,
  ApiPremiumStatusRoute: ApiPremiumStatusRoute,
  ApiSuggestRoute: ApiSuggestRoute,
  ApiWhopEventsRoute: ApiWhopEventsRoute,
  CheckoutPlanIdRoute: CheckoutPlanIdRoute,
  EatDishRoute: EatDishRoute,
  ExperiencesExperienceIdRoute: ExperiencesExperienceIdRoute,
  SeatIdRoute: SeatIdRoute,
  TogetherCodeRoute: TogetherCodeRoute,
  EatIndexRoute: EatIndexRoute,
  ApiOauthCallbackRoute: ApiOauthCallbackRoute,
  ApiOauthLoginRoute: ApiOauthLoginRoute,
  ApiOauthLogoutRoute: ApiOauthLogoutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
